numbagg/decorators.py, numbagg/moving.py, numbagg/test/test_funcs.py, numbagg/test/test_moving.py
`move_nanmean` didn't have tests and didn't work
I added a complication to the check for the window variable so we could use the same machinery. V open to a nicer way of accomplishing that...
=> Fix move, use ndmoving for ewm

README.rst, numbagg/__init__.py, numbagg/moving.py, numbagg/test/test_funcs.py, numbagg/test/test_moving.py
- Remove decorators from `__init__.py`.
- Rename `rolling_exp_nanmean` -> `move_exp_nanmean` for consistency.
- Update readme benchmarks for latest numba
=> Cleanup in preparation for public release

numbagg/decorators.py, numbagg/test/test_moving.py
Based on the discussion with @mathause https://github.com/pydata/xarray/pull/5178/files#r616168398.
I'm not sure whether this should go here, though. To the extent that xarray is the only library passing empty tuples as axis args, it should probably go back there. Happy to take direction!
=> Return original array when axis is empty tuple

benchmarks/benchmarks.py, numbagg/moving.py
The attempt to avoid divides was actually costing ~20% in performance, and the initial block was not contributing. This also makes the code simpler.
This is 3-4x faster than the equivalent pandas method...
=> Improve `move_mean` perf

numbagg/moving.py
This has no perf impact -- numba optimizes it away, but including for clarity
=> Use floats in inc/decr

numbagg/test/test_grouped.py
`x=5`, not `5=x`...
(with help from an LLM...)
=> Always have `result==expected` in tests

.gitignore, numbagg/decorators.py
Thanks to @dcherian for suggesting, in #145
The [warnings](https://numba.readthedocs.io/en/stable/user/jit.html#cache) look slightly alarming re using old versions of functions, but I don't _think_ they apply to us, since we're not calling other functions in different files, or using globals
Doesn't work on the standard reduce functions atm, can look into removing some of the numbagg customizations now that numba has come along
=> Use numba caching for group & moving functions

numbagg/decorators.py, numbagg/moving.py, numbagg/test/test_moving.py
Because we now accept multiple arrays, closing https://github.com/numbagg/numbagg/issues/61, this requires `alpha` to be kwarg-only. Which I think should be mostly fine...
=> Add `move_exp_nancov` function

.github/workflows/pypi-release.yaml
Sets up a race condition that can cause the release to fail
=> Don't double-push to test-pypi on release

numbagg/__init__.py, numbagg/moving.py, numbagg/test/test_moving.py
Pandas doesn't have this, but I find myself using it occasionally, and I think it makes sense, so adding it.
=> Add `move_exp_nancount` function

numbagg/funcs.py, numbagg/test/test_funcs.py, numbagg/test/test_moving.py
https://github.com/numbagg/numbagg/issues/138
This was already the case for the grouped and `rolling_exp` functions.
=> feat!: Set `ddof=1` as default for std & var functions

numbagg/decorators.py
The existing repr is extremely long, which makes for less legible benchmark views, etc
=> Shorten repr of functions

numbagg/decorators.py, numbagg/funcs.py, numbagg/grouped.py, numbagg/test/test_funcs.py, numbagg/test/test_grouped.py
This also does some general refactoring, and restricts a couple of functions from supplying ints — e.g. `group_nanstd`, which is a) not that useful and b) was causing some corner-case issues
=> Add `limit` option to `ffill` & `bfill`

numbagg/funcs.py, numbagg/test/conftest.py, numbagg/test/test_benchmark.py, numbagg/test/test_funcs.py
Broaden support for `nanquantile`, test across lots of axis values
=> `nanquantile` compatibility with `axis`

README.md, numbagg/decorators.py, numbagg/funcs.py, numbagg/grouped.py, numbagg/moving.py, numbagg/moving_exp.py, numbagg/test/conftest.py, numbagg/test/run_benchmarks.py, numbagg/test/test_benchmark.py
This refactors the wrapper, integrating all the function — including the wrap — into the class.
I don't _love_ it — we now have this `.wrap` method which needs to be used everywhere. I really tried to make it work without that, but I don't think it's possible — we have three stages:
- The decorator receives its arguments (but not the function): previously this was an additional function, is now the `.wrap` method
- The return value of that is then called with the function: this was & is the `__init__` method of the class
- The return value of that is then the function which users can call
The main issue is that we want the class's `__call__` for the third — I had tried returning something else, like a method or a function — but then we're exporting something unusual. And the `__init__` …
=> Fix nanquantile benchmarks, refactor wrapper

numbagg/decorators.py, numbagg/test/test_grouped.py
Pandas factorize returns smaller dtypes when possible.
=> Additional dtypes for labels.

.pre-commit-config.yaml, numbagg/decorators.py, numbagg/funcs.py
This was caused by an overflow, which we now prevent by ensuring we get a big enough dtype for the counts array.
Closes https://github.com/numbagg/numbagg/issues/211
=> Fix underlying int8 issue

numbagg/decorators.py, numbagg/funcs.py, numbagg/test/test_benchmark.py
One interesting observation — `nanquantile` is much much slower to compile — takes 3000ms. That seems to be because it has numpy functions in it.
https://github.com/numba/numba/issues/4807 would be really good to have, so we can cache between python runs. Atm we need to tradeoff runtime vs. start time — it's an easy call on a long-running program, which we _mostly_ have, but not always.
```
--------------------------------------------------------------------------------------------------------- benchmark: 16 tests ---------------------------------------------------------------------------------------------------------
Name (time in ms)                                                   Min                   Max                  Mean            StdDev                Median               IQR …
```
=> Benchmark compile times

numbagg/test/run_benchmarks.py, numbagg/test/test_benchmark.py
- Move more into the benchmark function, away from the script
- Defer setting parameters to `pytest-benchmark`, don't use `pedantic` mode
- Allow passing args to the script, rather than editing the files
From testing #159
=> De-layer the benchmarking code

numbagg/test/run_benchmarks.py, numbagg/test/test_benchmark.py
This lets us pass `--benchmark-max-time=0.1` or `=10` for varying precision
=> Move some more benchmark configs to CLI

README.md, numbagg/test/run_benchmarks.py
This is the output from `python numbagg/test/run_benchmarks.py -- --benchmark-max-time=10` and ensuring nothing else is running
=> More accurate benchmarks

numbagg/decorators.py, numbagg/grouped.py, numbagg/test/conftest.py, numbagg/test/test_grouped.py
I think easier to support this, in the end...
The code is quite ugly. This approach definitely wouldn't work for an arbitrary number of parameters. But for just `ddof`, which seems to be the primary heterodox one, it's possible
=> Add `ddof` param to group funcs

numbagg/decorators.py
A stray print found its way into the code. Leads to failed xarray doctests: https://github.com/pydata/xarray/actions/runs/7583203261/job/20654350361?pr=8629
=> remove stray print

numbagg/decorators.py, numbagg/funcs.py, numbagg/test/test_funcs.py, numbagg/test/test_moving.py, numbagg/test/util.py
With this PR `fastmath` optimizations can be optionally enabled via a `NUMBAGG_FASTMATH` environment variable. A warning is always issued when used. Importantly, we don't simply use `fastmath=True` but specify a set of [flags](https://llvm.org/docs/LangRef.html#fast-math-flags) that should not result in unsafe behavior, but possibly in reduced precision. The "no nans" and "no infs" fastmath flags are __not__ used. See also the discussion in #287. 
In my benchmarks I only observe a 2x performance improvement on `nansum` and `nanmean` (for double precision floats, in micro-benchmarks I saw 4x for single precision), smaller performance improvements on `nanstd` and `nanvar`, and no noticeable differences, or even slightly worse results, on all other aggregations.
Closes #287 
Tests are …
=> Optional fastmath optimizations via env var

numbagg/funcs.py
numpy 2 removes `np.infty` in favor of `np.inf`
=> numpy 2 compatibility

pyproject.toml
ruff wants `select` and `ignore` in a `lint` section
=> ruff config: add lint section

numbagg/test/test_funcs.py
Numbagg still doesn't support numpy 2. But we seem to run OK with it, with the exception of one error message
=> Allow different error messages with numpy 2

.github/workflows/test.yaml, numbagg/test/test_benchmark.py
Currently one function fails, and we weren't testing this in CI
=> Allow the compilation cost benchmarks to succeed

numbagg/decorators.py, numbagg/test/test_cache_segfault.py, pyproject.toml
In pursuit of https://github.com/numbagg/numbagg/issues/345, this adds some tests for whether we get segfaults.
It wasn't trivial to get working reproductions, and they depend on some delicate conditions, such as when the `__pycache__` paths were generated. Probably we can make the tests a bit smaller, but they do appear to work.
Unfortunately adding `_reload_parfors` doesn't seem to help; possibly because it's in the wrong place. I'll follow up with a PR with my current best attempt
=> Add tests for segfaulting with parallel + cache

.github/workflows/pypi-release.yaml
actions/upload-artifact@v5 and actions/download-artifact@v5 don't exist yet.
The latest available version is v4.
This was causing the v0.9.2 release to fail immediately.
After this is merged, we'll need to delete and recreate the v0.9.2 tag.
=> Fix GitHub Actions artifact versions
