- LICENSE
- README.rst
- numbagg/__init__.py
- numbagg/decorators.py
- numbagg/grouped.py
- numbagg/test/test_grouped.py
- setup.py
> Add groupndreduce and group_nanmean

- .travis.yml
- numbagg/__init__.py
- numbagg/cache.py
- numbagg/decorators.py
- numbagg/funcs.py
- numbagg/grouped.py
- numbagg/moving.py
- numbagg/test/test_funcs.py
- numbagg/test/test_grouped.py
- numbagg/test/test_moving.py
- numbagg/transform.py
- setup.py
I found this v good in other small projects, but obv your call @shoyer
I also dropped Py2 & Py3.4 testing and added 3.7
> black formatting

- numbagg/moving.py
- numbagg/test/test_moving.py
I'm moving too fast this morning and mistakenly deleted the branch attached to https://github.com/shoyer/numbagg/pull/16, and GH won't let me reopen the PR
Same code as the prior PR
> Rolling exp API

- numbagg/funcs.py
- numbagg/test/test_funcs.py
Numba can raise exceptions these days.
> Raise errors in reduce functions like NumPy

- numbagg/decorators.py
- numbagg/funcs.py
- numbagg/test/test_funcs.py
- numbagg/test/util.py
This should ensure that things work properly.
TODO: update test_moving.py with bottleneck tests, too.
> Update test_funcs.py with tests from bottleneck (and add fixes)

- .travis.yml
- README.rst
- numbagg/funcs.py
- numbagg/test/test_moving.py
- numbagg/transform.py
- setup.py
Also run black (and ensure travis actually checks black)
> Drop python 2 support

- .travis.yml
- numbagg/moving.py
- setup.cfg
Copied from xarray
Updated travis versions but it seems that's not working. Maybe we should replace with GH Actions at some point
> Update lint settings

- .github/workflows/pypi-release.yaml
- .github/workflows/test.yaml
- .pre-commit-config.yaml
- README.rst
- numbagg/moving.py
- setup.py
(requires uploading my PyPI key)
> Add release to PyPI workflow

- .pre-commit-config.yaml
- numbagg/__init__.py
Have just copied xarray's approach here
> Replace deprecated `pkg_resources`

- numbagg/moving.py
- numbagg/test/test_moving.py
I think this is much clearer...
> Simplify code in `moving_exp` functions

- numbagg/test/conftest.py
Makes looking at test logs quite difficult
> Silence numba debug logs

- .gitignore
- numbagg/moving.py
- numbagg/test/test_moving.py
~I haven't got the bias-free version working yet. I'll try and come back to it unless someone else could take a look...~
Working well; ~3-4x faster than pandas...
> Add `exp_nanvar` function

- numbagg/decorators.py
- numbagg/test/test_funcs.py
- numbagg/test/test_grouped.py
It's not sophisticated, and it's probably not fast, but it works.
Closes #122
> Have functions work for bools

- numbagg/decorators.py
- numbagg/grouped.py
- numbagg/test/test_grouped.py
- numbagg/test/test_moving.py
An LLM was actually very useful here, since it's mostly translating one existing form of a function to another conceptually existing form. So this was super quick, and tests well.
It needs a check. 
~And `sum_of_squares` needs a test, given there isn't a single pandas equivalent~ (done)
Closes #120, CC @dcherian
> Add grouped calcs

- numbagg/test/test_grouped.py
(though we should decide what behavior to adopt)
> Mute pandas warnings

- numbagg/decorators.py
This is now natively supported
> Delegate `validate_axis` to numba

- numbagg/moving.py
Xarray raised an error on not accepting an `axis` keyword. While the construction is very duplicative, it does cut through any complications, and is faster
> Implement `move_exp_nanstd` as a full function

- numbagg/grouped.py
I hit small issues when wrapping functions with the `move_exp_nanstd`, and given these are getting more use, it's safer to implement `group_nanstd` this way too, and slightly faster, since the sqrt is fused. 
It's not elegant!
(but I think we'd need something like Julia to be able to fuse the operations, and I'm not even sure Julia could do this given it's more than a simple broadcast...)
> Implement `group_nanstd` as a copy-paste

- numbagg/moving.py
Where `bias` was zero, this could happen.
I'll add tests with the new test functions that I'm planning to publish
> Ensure we don't produce `inf` values

- numbagg/test/__init__.py
- numbagg/test/test_moving.py
...which we can use for benchmarks too.
Starting with the `move_exp_nan*` functions
> Start creating a generalized test infrastructure

- numbagg/decorators.py
I'm getting SIGABRT errors locally with caching, now that `parallel` is turned on. I can investigate, but for the moment let's disable to ensure stability
> Disable caching

- README.md
- numbagg/decorators.py
Reduce some code duplication, work towards supporting `axis` natively (given it's now supported in `numpy` for gufuncs).
> Refactoring, support `axis` more natively

- numbagg/decorators.py
- numbagg/test/conftest.py
- numbagg/test/test_multithreading.py
https://github.com/numba/numba/issues/9288 for background
> Check multithreading context on each call, stop using `parallel` if we're in one

- numbagg/decorators.py
Closes https://github.com/numbagg/numbagg/issues/209
> Only disable `parallel` on workqueue backend

- numbagg/decorators.py
- numbagg/test/test_grouped.py
This doesn't completely fix the underlying issue — it instead has numba coerce to a larger type IIUC. It fixes the symptoms, and I'll come back to work through what's going on.
> Patch `int8` issue

- numbagg/decorators.py
- numbagg/test/conftest.py
> Also use target logic for grouped functions

- .github/workflows/test.yaml
- numbagg/funcs.py
- numbagg/test/test_multithreading.py
> Make warnings in CI into errors

- .github/workflows/test.yaml
- conftest.py
- numbagg/decorators.py
- numbagg/test/conftest.py
- numbagg/test/run_benchmarks.py
- numbagg/test/test_benchmark.py
- numbagg/test/test_grouped.py
- numbagg/test/test_multithreading.py
- pyproject.toml
General refactoring, getting the group benchmarks into a better state
> Improve benchmarks

- numbagg/decorators.py
> Reduce compile-time costs by limiting signature count (small)

- README.md
- numbagg/funcs.py
- numbagg/test/run_benchmarks.py
Also reverts some changes to functions that made them much slower! (I should have checked first)
> Add all functions to benchmarks, consolidate benchmark summary

- numbagg/test/run_benchmarks.py
Was preventing us from running on only `group` functions, since those don't run on bottleneck.
> Condense benchmark code

- numbagg/test/test_grouped.py
> Add multiple funcs to int8 tests

- numbagg/funcs.py
- numbagg/test/conftest.py
- numbagg/test/test_funcs.py
> Fix nanquantile mutating its input

- numbagg/decorators.py
- numbagg/funcs.py
- numbagg/moving.py
- numbagg/moving_exp.py
- numbagg/test/test_utils.py
- numbagg/test/util.py
- numbagg/utils.py
Add an aggregate (aka reduce) decorator in the "new style", which supports scalar args such as ddof, and use those for std & var
> Add `ddof` to aggregate functions, add new decorator

- .pre-commit-config.yaml
> Don't allow `print` statements into code

- .pre-commit-config.yaml
No longer pre-commit, since it's been failing for a while and I can't work out why...
> Run mypy in GHA only

- numbagg/test/conftest.py
- numbagg/test/test_grouped.py
> Remove `supports_nd` attribute

- numbagg/decorators.py
Previous PR didn't include the main change
> Actually remove `supports_nd`

- numbagg/decorators.py
- numbagg/grouped.py
- numbagg/test/test_grouped.py
As an effort to improve JIT performance
~(also fixes a small bug that invalid types now raise an error)~
> Cache grouped functions by type
